# pandas 进阶修炼 ｜早起Python

**本习题由公众号【早起Python & 可视化图鉴】 原创，授权「和鲸社区」独家第三方平台发布。**


**转载及其他形式合作请与我们联系，未经授权严禁搬运及二次创作，侵权必究！**



本习题基于 `pandas` 版本 `1.1.3`，所有内容应当在 `Jupyter Notebook` 中执行以获得最佳效果。

不同版本之间写法可能会有少许不同，如若碰到此情况，你应该学会如何自行检索解决。

## 7 - 数据透视与合并



    
现在让我们继续练习 pandas数据分析另一组常用操作 --> **数据透视与合并**


本节习题将涉及四大函数：
    
- pivot_table
- concat
- merge
- join

随着练习的深入，若没有一定的基础知识将很难继续刷题
    
官方文档永远是最好的学习手册，在本节之前强烈建议学习[官方文档对应部分](https://pandas.pydata.org/pandas-docs/version/0.20/merging.html#database-style-dataframe-joining-merging)

## 初始化



该 `Notebook` 版本为**习题+答案版**


请执行下方单元格以初始化读取本节习题的答案

执行完毕后，你可以使用 `ans(1)` 来查看第 1 题的参考解答，其余习题类似。

注意：所有答案并非固定（唯一），我提供的答案仅供参考（并非推荐答案或者最优解）

如果发现任何错误或者你有更好的解答，可以微信搜索公众号「早起Python」提交以获得奖励！

In [5]:
### 请务必执行本单元格加载本章所需要的数据与答案！
### 本单元格仅需执行一次！
### 由于和鲸社区数据缓存有一定时效，如若在后续的使用过程中出现数据文件不存在的问题，请重新执行本单元格以加载数据
# ! mkdir data7 > /dev/null 2>&1 && wget http://101.34.8.201:8080/pandas300/data/data7.zip > /dev/null 2>&1 && unzip /home/mw/project/data7.zip -d /home/mw/project/data7 > /dev/null 2>&1

import sys
import os
import pandas as pd
os.chdir('/home/ywd/workspace/python/pandas-tk/data7')
print(os.getcwd())
from inits import initialize,ans
res = initialize("answer-7.txt")

/home/ywd/workspace/python/pandas-tk/data7
***************正在初始化***************
*************读取到配置文件*************
***************初始化成功***************

## 数据透视表

![](http://liuzaoqi.oss-cn-beijing.aliyuncs.com/2021/09/14/16316101294678.jpg?域名/sample.jpg?x-oss-process=style/stylename)

### 1 - 加载数据

读取当前目录下 `"某超市销售数据.csv"` 并设置千分位符号为 `,`

In [10]:
df = pd.read_csv('某超市销售数据.csv',thousands=',')
df

,订单ID,订单日期,邮寄方式,国家,地区,省/自治区,细分,类别,子类别,制造商,产品名称,数量,销售额,利润
0,A1000001,2013/1/1,二级,中国,中南,湖南,公司,办公用品,收纳具,Rogers,"Rogers 文件车, 单宽度",5,3305,1322
1,A1000001,2013/1/1,二级,中国,中南,湖南,公司,家具,桌子,Barricks,"Barricks 圆桌, 白色",3,5289,-635
2,A1000001,2013/1/1,二级,中国,中南,湖南,公司,技术,电话,诺基亚,"诺基亚 智能手机, 整包",3,1725,69
3,A1000001,2013/1/1,二级,中国,中南,湖南,公司,技术,配件,贝尔金,"贝尔金 记忆卡, 实惠",3,1607,611
4,A1000003,2013/1/2,二级,中国,华东,福建,消费者,办公用品,收纳具,Rogers,"Rogers 盒, 工业",4,456,128
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9930,A1004918,2016/12/30,标准级,中国,中南,广东,消费者,技术,复印机,夏普,"夏普 墨水, 红色",1,343,-172
9931,A1004918,2016/12/30,标准级,中国,中南,广东,消费者,技术,电话,三星,"三星 音频基座, 蓝色",2,934,-389
9932,A1004924,2016/12/30,标准级,中国,中南,广东,公司,技术,设备,松下,"松下 收据打印机, 耐用",4,1355,-113
9933,A1004924,2016/12/30,标准级,中国,中南,广东,公司,技术,配件,Enermax,"Enermax 键区, 回收",5,772,-181
9934,A1004919,2016/12/30,标准级,中国,中南,湖南,消费者,办公用品,信封,GlobeWeis,"GlobeWeis 搭扣信封, 回收",3,122,18

### 2 - 数据透视｜默认

制作各省「平均销售额」的数据透视表

In [14]:
df.pivot_table(index='省/自治区',values='销售额', aggfunc=['mean'])

              mean
               销售额
省/自治区
上海     1875.712934
云南     1863.789030
内蒙古    1314.826316
北京     1726.857143
吉林     1701.563567
四川     1157.875536
天津     1611.206667
宁夏     1651.680000
安徽     1477.868251
山东     1642.659111
山西     1751.359184
广东     1592.185340
广西     1675.061135
新疆     1402.384615
江苏     1279.898089
江西     1966.477876
河北     1780.275248
河南     1558.400335
浙江     1347.277778
海南     1721.982759
湖北     1324.808442
湖南     1603.702222
甘肃     1602.893443
福建     1732.044693
西藏      201.000000
贵州     1425.978723
辽宁     1363.381982
重庆     1383.082927
陕西     1880.606635
青海     2978.954545
黑龙江    1800.438503

### 3 - 数据透视｜指定方法

制作各省「销售总额」的数据透视表

In [15]:
ans(3)
df.pivot_table(index='省/自治区',values='销售额', aggfunc=['sum'])

pd.pivot_table(df,values = ['销售额'],index = '省/自治区',aggfunc = sum)

           sum
           销售额
省/自治区
上海      594601
云南      441718
内蒙古     249817
北京      350552
吉林      896724
四川      269785
天津      483362
宁夏       41292
安徽      684253
山东     1884130
山西      429083
广东     1520537
广西      383589
新疆       72924
江苏      401888
江西      222212
河北      899039
河南      930365
浙江      266761
海南       99875
湖北      408041
湖南      721666
甘肃      195553
福建      620072
西藏         201
贵州       67021
辽宁      756677
重庆      283532
陕西      396808
青海       65537
黑龙江    1346728

### 4 - 数据透视｜多方法

制作各省「销售总额」与「平均销售额」的数据透视表

In [16]:
df.pivot_table(index='省/自治区',values='销售额', aggfunc=['sum','mean'])

           sum         mean
           销售额          销售额
省/自治区
上海      594601  1875.712934
云南      441718  1863.789030
内蒙古     249817  1314.826316
北京      350552  1726.857143
吉林      896724  1701.563567
四川      269785  1157.875536
天津      483362  1611.206667
宁夏       41292  1651.680000
安徽      684253  1477.868251
山东     1884130  1642.659111
山西      429083  1751.359184
广东     1520537  1592.185340
广西      383589  1675.061135
新疆       72924  1402.384615
江苏      401888  1279.898089
江西      222212  1966.477876
河北      899039  1780.275248
河南      930365  1558.400335
浙江      266761  1347.277778
海南       99875  1721.982759
湖北      408041  1324.808442
湖南      721666  1603.702222
甘肃      195553  1602.893443
福建      620072  1732.044693
西藏         201   201.000000
贵州       67021  1425.978723
辽宁      756677  1363.381982
重庆      283532  1383.082927
陕西      396808  1880.606635
青海       65537  2978.954545
黑龙江    1346728  1800.438503

### 5 - 数据透视｜多指标

制作各省市「销售总额」与「利润总额」的数据透视表

In [17]:
df.pivot_table(index='省/自治区',values=['销售额','利润'], aggfunc=['sum'])

          sum
           利润      销售额
省/自治区
上海      87236   594601
云南      83201   441718
内蒙古    -20685   249817
北京      57883   350552
吉林     152504   896724
四川     -16615   269785
天津      63108   483362
宁夏      -1149    41292
安徽     133312   684253
山东     310042  1884130
山西      79913   429083
广东     278591  1520537
广西      61444   383589
新疆      13696    72924
江苏      -6500   401888
江西      27144   222212
河北     153247   899039
河南     168714   930365
浙江     -17024   266761
海南      21298    99875
湖北     -22896   408041
湖南      92944   721666
甘肃     -25298   195553
福建     133791   620072
西藏          4      201
贵州       5408    67021
辽宁     -24930   756677
重庆      39688   283532
陕西      61753   396808
青海       4354    65537
黑龙江    228262  1346728

### 6 - 数据透视｜多索引

制作「各省市」与「不同类别」产品「销售总额」的数据透视表

In [21]:
df.pivot_table(index=['省/自治区','类别'],values='销售额', aggfunc=['sum'])

               sum
               销售额
省/自治区 类别
上海    办公用品  198529
      家具    221058
      技术    175014
云南    办公用品  123051
      家具    174155
...            ...
青海    家具     25923
      技术     22896
黑龙江   办公用品  473319
      家具    497504
      技术    375905

[91 rows x 1 columns]

### 7 - 数据透视｜多层

制作各省市「不同类别」产品的「销售总额」透视表

In [23]:
df.pivot_table(index=['省/自治区'],values='销售额', columns='类别',aggfunc=['sum'])

            sum
类别         办公用品        家具        技术
省/自治区
上海     198529.0  221058.0  175014.0
云南     123051.0  174155.0  144512.0
内蒙古     74058.0   95426.0   80333.0
北京     144232.0  127407.0   78913.0
吉林     215143.0  287498.0  394083.0
四川     111393.0   88297.0   70095.0
天津     142526.0  149452.0  191384.0
宁夏      19529.0   16449.0    5314.0
安徽     200511.0  215901.0  267841.0
山东     575520.0  664339.0  644271.0
山西     121458.0  175522.0  132103.0
广东     494643.0  530054.0  495840.0
广西     102625.0  165140.0  115824.0
新疆      38345.0   20520.0   14059.0
江苏     163919.0  152868.0   85101.0
江西      37114.0  107047.0   78051.0
河北     284739.0  306535.0  307765.0
河南     266916.0  294593.0  368856.0
浙江      84471.0   84436.0   97854.0
海南      34141.0   41225.0   24509.0
湖北     112230.0  118053.0  177758.0
湖南     197969.0  241804.0  281893.0
甘肃      54012.0   68657.0   72884.0
福建     142728.0  243289.0  234055.0
西藏        201.0       NaN       NaN
贵州       9713.0   29285.0   28023.0
辽宁     214994.0  270279.0  271404.0
重庆      71020.0   96318.0  116194.0
陕西     119169.0  187497.0   90142.0
青海      16718.0   25923.0   22896.0
黑龙江    473319.0  497504.0  375905.0

### 8 - 数据透视｜综合

制作「各省市」、「不同类别」产品「销售量与销售额」的「均值与总和」的数据透视表，并在最后追加一行『合计』

In [29]:
ans(8)
df.pivot_table(index=['省/自治区','类别'],values=['数量','销售额'],aggfunc=['mean','sum'],margins=True)

pd.pivot_table(df,values = ['销售额','数量'],index = ['省/自治区','类别'],aggfunc = ['mean',sum],margins=True)

                mean                 sum
                  数量          销售额     数量       销售额
省/自治区 类别
上海    办公用品  3.706897  1140.971264    645    198529
      家具    4.132530  2663.349398    343    221058
      技术    3.616667  2916.900000    217    175014
云南    办公用品  3.913043   891.673913    540    123051
      家具    4.224490  3554.183673    207    174155
...              ...          ...    ...       ...
青海    技术    3.833333  3816.000000     23     22896
黑龙江   办公用品  3.657471  1088.089655   1591    473319
      家具    3.921687  2997.012048    651    497504
      技术    3.442177  2557.176871    506    375905
All         3.768093  1608.892099  37436  15984343

[92 rows x 4 columns]

### 9 - 数据透视｜筛选

在上一题的基础上，查询 **「类别」** 等于 **「办公用品」** 的详情

In [31]:
ans(9)
table = df.pivot_table(index=['省/自治区','类别'],values=['数量','销售额'],aggfunc=['mean','sum'],margins=True)
table.query('类别 == ["办公用品"]')

table = pd.pivot_table(df,values = ['销售额','数量'],index = ['省/自治区','类别'],aggfunc = ['mean',sum],margins=True)
table.query('类别 == ["办公用品"]')

                mean                sum
                  数量          销售额    数量     销售额
省/自治区 类别
上海    办公用品  3.706897  1140.971264   645  198529
云南    办公用品  3.913043   891.673913   540  123051
内蒙古   办公用品  3.391304   643.982609   390   74058
北京    办公用品  3.750000  1163.161290   465  144232
吉林    办公用品  3.520270   726.834459  1042  215143
四川    办公用品  3.947368   837.541353   525  111393
天津    办公用品  3.917127   787.436464   709  142526
宁夏    办公用品  3.750000  1627.416667    45   19529
安徽    办公用品  3.710526   753.800752   987  200511
山东    办公用品  3.775112   862.848576  2518  575520
山西    办公用品  3.880597   906.402985   520  121458
广东    办公用品  3.908088   909.270221  2126  494643
广西    办公用品  3.954545   777.462121   522  102625
新疆    办公用品  3.575758  1161.969697   118   38345
江苏    办公用品  3.849741   849.321244   743  163919
江西    办公用品  3.523077   570.984615   229   37114
河北    办公用品  3.968750   988.677083  1143  284739
河南    办公用品  3.628242   769.210375  1259  266916
浙江    办公用品  3.684211   740.973684   420   84471
海南    办公用品  3.314286   975.457143   116   34141
湖北    办公用品  3.666667   645.000000   638  112230
湖南    办公用品  3.629771   755.606870   951  197969
甘肃    办公用品  4.206349   857.333333   265   54012
福建    办公用品  3.801047   747.267016   726  142728
西藏    办公用品  3.000000   201.000000     3     201
贵州    办公用品  3.954545   441.500000    87    9713
辽宁    办公用品  3.741722   711.900662  1130  214994
重庆    办公用品  3.876106   628.495575   438   71020
陕西    办公用品  3.816667   993.075000   458  119169
青海    办公用品  4.444444  1857.555556    40   16718
黑龙江   办公用品  3.657471  1088.089655  1591  473319

### 10 -数据透视｜逆透视

逆透视就是将宽的表转换为长的表，例如将第 5 题的透视表进行逆透视，其中不需要转换的列为『数量』列

微信搜索公众号「早起Python」，关注后可以获得更多资源！`

## 数据合并

### concat - 数据拼接

`concat`主要用于**数据拼接**，也是非常常用的一个操作

除了官方文档外很难找到比官方文档更好的练习

以下案例来源或基于 [👉官方文档](https://pandas.pydata.org/pandas-docs/version/0.20/merging.html) 中的案例修改而来

在练习之前应执行下方代码生成数据

并应预览不同数据的结构以及每题的图解（如果有）

In [32]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']},
                   index=[0, 1, 2, 3])


df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                    'B': ['B4', 'B5', 'B6', 'B7'],
                    'C': ['C4', 'C5', 'C6', 'C7'],
                    'D': ['D4', 'D5', 'D6', 'D7']},
                   index=[4, 5, 6, 7])


df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                    'B': ['B8', 'B9', 'B10', 'B11'],
                    'C': ['C8', 'C9', 'C10', 'C11'],
                    'D': ['D8', 'D9', 'D10', 'D11']},
                   index=[8, 9, 10, 11])


df4 = pd.DataFrame({'B': ['B2', 'B3', 'B6', 'B7'],
                    'D': ['D2', 'D3', 'D6', 'D7'],
                    'F': ['F2', 'F3', 'F6', 'F7']},
                   index=[2, 3, 6, 7])

In [33]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [34]:
df2

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [35]:
df3

      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [36]:
df4

    B   D   F
2  B2  D2  F2
3  B3  D3  F3
6  B6  D6  F6
7  B7  D7  F7

#### 11 - concat｜默认拼接

拼接 df1 和 df2

In [42]:
pd.concat([df1,df2])

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

#### 12 - concat｜拼接多个

垂直拼接 `df1、df2、df3`，效果如下图所示

![](https://pandas.pydata.org/pandas-docs/version/0.20/_images/merging_concat_basic.png)

In [45]:
pd.concat([df1,df2,df3])

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

#### 13 - concat｜重置索引

垂直拼接 df1 和 df4，并按顺序重新生成索引，

![](https://pandas.pydata.org/pandas-docs/version/0.20/_images/merging_concat_ignore_index.png)

In [50]:
rs = pd.concat([df1,df4], ignore_index=True)
ans(13)

pd.concat([df1, df4], ignore_index=True)

微信搜索公众号「早起Python」，关注后可以获得更多资源！

#### 14 - concat｜横向拼接

横向拼接 `df1、df4`，效果如下图所示


![](https://pandas.pydata.org/pandas-docs/version/0.20/_images/merging_concat_axis1.png)

In [51]:
pd.concat([df1,df4], axis=1)

     A    B    C    D    B    D    F
0   A0   B0   C0   D0  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN
2   A2   B2   C2   D2   B2   D2   F2
3   A3   B3   C3   D3   B3   D3   F3
6  NaN  NaN  NaN  NaN   B6   D6   F6
7  NaN  NaN  NaN  NaN   B7   D7   F7

#### 15 - concat｜横向拼接（取交集）

在上一题的基础上，只取结果的交集

![](https://pandas.pydata.org/pandas-docs/version/0.20/_images/merging_concat_axis1_inner.png)

In [54]:
ans(15)
pd.concat([df1,df4], axis=1, join='inner')

pd.concat([df1,df4],axis=1,join='inner')

    A   B   C   D   B   D   F
2  A2  B2  C2  D2  B2  D2  F2
3  A3  B3  C3  D3  B3  D3  F3

#### 16 - concat｜横向拼接（取指定）

在 14 题基础上，只取包含 df1 索引的部分

![](https://pandas.pydata.org/pandas-docs/version/0.20/_images/merging_concat_axis1_join_axes.png)

In [56]:
pd.concat([df1,df4], axis=1).reindex(df1.index)

    A   B   C   D    B    D    F
0  A0  B0  C0  D0  NaN  NaN  NaN
1  A1  B1  C1  D1  NaN  NaN  NaN
2  A2  B2  C2  D2   B2   D2   F2
3  A3  B3  C3  D3   B3   D3   F3

![公众号：早起Python](http://liuzaoqi.oss-cn-beijing.aliyuncs.com/2021/09/18/16319660121648.jpg?域名/sample.jpg?x-oss-process=style/stylename)

#### 17 - concat｜新增索引

拼接 `df1、df2、df3`，同时新增一个索引（`x、y、z`）来区分不同的表数据来源

![](https://pandas.pydata.org/pandas-docs/version/0.20/_images/merging_concat_keys.png)

In [58]:
pd.concat([df1,df2,df3],keys=['x','y','z'])

        A    B    C    D
x 0    A0   B0   C0   D0
  1    A1   B1   C1   D1
  2    A2   B2   C2   D2
  3    A3   B3   C3   D3
y 4    A4   B4   C4   D4
  5    A5   B5   C5   D5
  6    A6   B6   C6   D6
  7    A7   B7   C7   D7
z 8    A8   B8   C8   D8
  9    A9   B9   C9   D9
  10  A10  B10  C10  D10
  11  A11  B11  C11  D11

### merge - 数据连接

concat是拼接，merge则是连接，同样重要的一个操作

同样很难找到比官方文档更好的练习，以下案例来源或基于 [👉官方文档](https://pandas.pydata.org/pandas-docs/version/0.20/merging.html#database-style-dataframe-joining-merging) 中的案例修改而来

在练习之前应执行每题下方的代码生成数据

并应预览不同数据的结构以及每题的图解（如果有）

#### 18 - merge｜按单键

根据 `key` 连接 `left` 和 `right`

![](https://pandas.pydata.org/pandas-docs/version/0.20/_images/merging_merge_on_key.png)

In [65]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})

right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                      'C': ['C0', 'C1', 'C2', 'C3'],
                      'D': ['D0', 'D1', 'D2', 'D3']})

In [66]:
# ans(18)
pd.merge(left, right, on='key')

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

#### 19 - merge｜按多键

根据 `key1` 和 `key2` 连接 `left` 和 `right`

![](https://pandas.pydata.org/pandas-docs/version/0.20/_images/merging_merge_on_key_multiple.png)

In [67]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})


right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                      'key2': ['K0', 'K0', 'K0', 'K0'],
                      'C': ['C0', 'C1', 'C2', 'C3'],
                      'D': ['D0', 'D1', 'D2', 'D3']})

In [72]:
pd.merge(left, right, left_on='key1',right_on='key2')
# ans(19)
# pd.merge(left, right, on=['key1', 'key2'])

  key1_x key2_x   A   B key1_y key2_y   C   D
0     K0     K0  A0  B0     K0     K0  C0  D0
1     K0     K0  A0  B0     K1     K0  C1  D1
2     K0     K0  A0  B0     K1     K0  C2  D2
3     K0     K0  A0  B0     K2     K0  C3  D3
4     K0     K1  A1  B1     K0     K0  C0  D0
5     K0     K1  A1  B1     K1     K0  C1  D1
6     K0     K1  A1  B1     K1     K0  C2  D2
7     K0     K1  A1  B1     K2     K0  C3  D3

#### 20 - merge｜左外连接


如下图所示的结果连接 left 和 right，保留左表全部键
![](https://pandas.pydata.org/pandas-docs/version/0.20/_images/merging_merge_on_key_left.png)

In [75]:
pd.merge(left, right, how='left',on=['key1','key2'])

  key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   K1  A3  B3  NaN  NaN

#### 21 - merge｜右外连接


如下图所示的结果连接 left 和 right，保留右表全部键
![](https://pandas.pydata.org/pandas-docs/version/0.20/_images/merging_merge_on_key_right.png)

In [78]:
pd.merge(left, right, how='right',on=['key1','key2'])

  key1 key2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

#### 22 -merge｜全外连接


如下图所示的结果连接 left 和 right，保留全部键
![](https://pandas.pydata.org/pandas-docs/version/0.20/_images/merging_merge_on_key_outer.png)

In [80]:
pd.merge(left, right, how='outer',on=['key1','key2'])

  key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K1   A3   B3  NaN  NaN
5   K2   K0  NaN  NaN   C3   D3

#### 23 -merge｜内连接


如下图所示的结果连接 left 和 right，保留交集
![](https://pandas.pydata.org/pandas-docs/version/0.20/_images/merging_merge_on_key_inner.png)

In [82]:
pd.merge(left, right, how='inner',on=['key1','key2'])

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

#### 24 - merge｜重复索引


重新产生数据并按下图所示进行连接
![](https://pandas.pydata.org/pandas-docs/version/0.20/_images/merging_merge_overlapped_suffix.png)

In [83]:
left = pd.DataFrame({'k': ['K0', 'K1', 'K2'], 'v': [1, 2, 3]})

right = pd.DataFrame({'k': ['K0', 'K0', 'K3'], 'v': [4, 5, 6]})

### join - 组合

最后一个数据合并的常用且重要的操作是`join`

同样很难找到比官方文档更好的练习，以下案例来源或基于 [👉官方文档](https://pandas.pydata.org/pandas-docs/version/0.20/merging.html#database-style-dataframe-joining-merging) 中的案例修改而来

在练习之前应执行每题下方的代码生成数据

并应预览不同数据的结构以及每题的图解（如果有）

In [84]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                     index=['K0', 'K1', 'K2'])


right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                      'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

#### 25 - join｜左对齐

合并 left 和 right，并按照 left 的索引进行对齐

![](https://pandas.pydata.org/pandas-docs/version/0.20/_images/merging_join.png)

In [87]:
# pd.merge(left,right)
ans(25)
left.join(right)

left.join(right)

     A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

#### 26 -join｜左对齐（外连接）

按下图所示进行连接

思考：merge 做法

![](https://pandas.pydata.org/pandas-docs/version/0.20/_images/merging_join_outer.png)

In [90]:
pd.merge(left, right, how='outer', left_index=True, right_index=True)
# ans(26)

      A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

#### 27 - join｜左对齐（内连接）

按下图所示进行连接

![](https://pandas.pydata.org/pandas-docs/version/0.20/_images/merging_join_inner.png)

In [91]:
pd.merge(left, right, how='inner', left_index=True, right_index=True)

     A   B   C   D
K0  A0  B0  C0  D0
K2  A2  B2  C2  D2

#### 28 -join｜按索引

重新产生数据并按下图所示进行连接（根据 `key`）

![](https://pandas.pydata.org/pandas-docs/version/0.20/_images/merging_join_key_columns.png)

In [92]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3'],
                     'key': ['K0', 'K1', 'K0', 'K1']})


right = pd.DataFrame({'C': ['C0', 'C1'],
                      'D': ['D0', 'D1']},
                      index=['K0', 'K1'])

In [94]:
pd.merge(left, right, how='outer', left_on='key', right_index=True)
ans(28)

left.join(right, on='key')

#### 29 - join｜按索引（多个）

重新产生数据并按下图所示进行连接（根据 `key1` 和 `key2`）

![](https://pandas.pydata.org/pandas-docs/version/0.20/_images/merging_join_multikeys.png)

In [ ]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3'],
                     'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1']})


index = pd.MultiIndex.from_tuples([('K0', 'K0'), ('K1', 'K0'),
                                  ('K2', 'K0'), ('K2', 'K1')])


right = pd.DataFrame({'C': ['C0', 'C1', 'C2', 'C3'],
                   'D': ['D0', 'D1', 'D2', 'D3']},
                  index=index)

![](http://liuzaoqi.oss-cn-beijing.aliyuncs.com/2021/09/16/16317972442543.jpg?域名/sample.jpg?x-oss-process=style/stylename)